/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.CustomerRole;

import Business.Customer.Customer;
import Business.EcoSystem;
import Business.Orders.OrderDirectory;

import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import userinterface.GroceryAdminRole.ManageGroceryInventoryPanel;
import userinterface.GroceryAdminRole.ManageOrdersPanel;

/**
 *
 * @author shikha
 */
public class CustomerAreaJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    EcoSystem ecosystem;
    DefaultTableModel model1;
    private UserAccount userAccount;
    private OrderDirectory orderDirectory;
    DefaultTableModel model;
    Customer cust;
    public CustomerAreaJPanel(JPanel userProcessContainer, UserAccount account, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        ecosystem = system;
        cust = findCustomer();

        //valueLabel.setText(enterprise.getName());
        title2.setText("Welcome "+ cust.getName());
        
        ImageIcon icon1 =  new ImageIcon("./src/images/customer_panel_profile.png");
        Image image1 = icon1.getImage().getScaledInstance(75, 50, Image.SCALE_SMOOTH);
        CovidCare1.setIcon(new ImageIcon(image1));
        
        ImageIcon icon2 =  new ImageIcon("./src/images/forbidden.png");
        Image image2 = icon2.getImage().getScaledInstance(75, 60, Image.SCALE_SMOOTH);
        legalbutton.setIcon(new ImageIcon(image2));
        
        ImageIcon icon3 =  new ImageIcon("./src/images/grocery_customer_panel.png");
        Image image3 = icon3.getImage().getScaledInstance(75, 30, Image.SCALE_SMOOTH);
        grocerybutton.setIcon(new ImageIcon(image3));
        
        ImageIcon icon4 =  new ImageIcon("./src/images/cutomer_panel_maid1.png");
        Image image4 = icon4.getImage().getScaledInstance(75, 50, Image.SCALE_SMOOTH);
        maidbutton.setIcon(new ImageIcon(image4));
        
        ImageIcon icon5 =  new ImageIcon("./src/images/customer_panel_therepist.png");
        Image image5 = icon5.getImage().getScaledInstance(75, 50, Image.SCALE_SMOOTH);
        therpistbutton.setIcon(new ImageIcon(image5));
        
        ImageIcon icon6 =  new ImageIcon("./src/images/customer_panel_hotel.png");
        Image image6 = icon6.getImage().getScaledInstance(75, 40, Image.SCALE_SMOOTH);
        hotelbutton.setIcon(new ImageIcon(image6));
        
        ImageIcon icon7 =  new ImageIcon("./src/images/customer_panel_cart.png");
        Image image7 = icon7.getImage().getScaledInstance(75, 60, Image.SCALE_SMOOTH);
        cartbutton.setIcon(new ImageIcon(image7));
        
        ImageIcon icon8 =  new ImageIcon("./src/images/customer_panel_payment.png");
        Image image8 = icon8.getImage().getScaledInstance(75, 60, Image.SCALE_SMOOTH);
        cardbutton.setIcon(new ImageIcon(image8));
        
        ImageIcon icon9 =  new ImageIcon("./src/images/PicsArt_12-11-06.26.57.jpg");
        Image image9 = icon9.getImage().getScaledInstance(250, 260, Image.SCALE_SMOOTH);
        birdiemessage.setIcon(new ImageIcon(image9));
        
        
 }
    
     public Customer findCustomer() {
        for (int i = 0; i < ecosystem.getCustomerDirectory().getCustomerList().size(); i++) {
            if (ecosystem.getCustomerDirectory().getCustomerList().get(i).getAccountDetails().getUsername().equals(this.userAccount.getUsername())) {
                return ecosystem.getCustomerDirectory().getCustomerList().get(i);
            }
        }
        return null;
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        legalbutton = new javax.swing.JButton();
        grocerybutton = new javax.swing.JButton();
        maidbutton = new javax.swing.JButton();
        therpistbutton = new javax.swing.JButton();
        hotelbutton = new javax.swing.JButton();
        CovidCare1 = new javax.swing.JButton();
        cartbutton = new javax.swing.JButton();
        cardbutton = new javax.swing.JButton();
        container = new javax.swing.JPanel();
        title2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        birdiemessage = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        title = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jSplitPane1.setBackground(new java.awt.Color(255, 255, 255));
        jSplitPane1.setDividerLocation(200);
        jSplitPane1.setDividerSize(10);

        jPanel1.setBackground(new java.awt.Color(240, 248, 255));
        jPanel1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        legalbutton.setText("Legal");
        legalbutton.setBorder(null);
        legalbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                legalbuttonActionPerformed(evt);
            }
        });

        grocerybutton.setText("Grocery");
        grocerybutton.setBorder(null);
        grocerybutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grocerybuttonActionPerformed(evt);
            }
        });

        maidbutton.setText("Household");
        maidbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maidbuttonActionPerformed(evt);
            }
        });

        therpistbutton.setText("Therapy");
        therpistbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                therpistbuttonActionPerformed(evt);
            }
        });

        hotelbutton.setText("Food");
        hotelbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hotelbuttonActionPerformed(evt);
            }
        });

        CovidCare1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        CovidCare1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/customer_panel_profile.png"))); // NOI18N
        CovidCare1.setText("Profile");
        CovidCare1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CovidCare1ActionPerformed(evt);
            }
        });

        cartbutton.setText("Cart");
        cartbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cartbuttonActionPerformed(evt);
            }
        });

        cardbutton.setText("Add Card");
        cardbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cardbutton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(legalbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(grocerybutton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(maidbutton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(therpistbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hotelbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cartbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CovidCare1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(CovidCare1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(legalbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(grocerybutton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(maidbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(therpistbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(hotelbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(cartbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(cardbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(275, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(jPanel1);

        container.setBackground(new java.awt.Color(255, 255, 255));
        container.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title2.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        title2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title2.setText("HEY THERE MY FRIEND");
        container.add(title2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 600, 60));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("See our bird flying? That's your guide in this app world");
        container.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("Hey we know you are missing all the fun sitting at home!");
        container.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setText("Dont worry we have got you covered!");
        container.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setText("From A-Z everything on your fingertips");
        container.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        birdiemessage.setText(" ");
        container.add(birdiemessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 20, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("© All Copyrights, PAY technologies and private Limited");
        container.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 720, -1, 30));

        title.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/customer_panel_1 copy.gif"))); // NOI18N
        title.setText("jLabel3");
        container.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 940, 820));

        jSplitPane1.setRightComponent(container);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void legalbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_legalbuttonActionPerformed
        CustomerOrderLegalPanel mm = new CustomerOrderLegalPanel(userProcessContainer, userAccount, ecosystem, jSplitPane1);
//        userProcessContainer.add("manageNetworkJPanel",mm);
//        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
//        layout.next(userProcessContainer);        // TODO add your handling code here:
        jSplitPane1.setRightComponent(mm);
    }//GEN-LAST:event_legalbuttonActionPerformed

    private void grocerybuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grocerybuttonActionPerformed
        OrderGroceryPanel mm = new OrderGroceryPanel(userProcessContainer, userAccount, ecosystem, jSplitPane1);
//        userProcessContainer.add("manageNetworkJPanel",mm);
//        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
//        layout.next(userProcessContainer);
        // TODO add your handling code here:        // TODO add your handling code here:
        jSplitPane1.setRightComponent(mm);
    }//GEN-LAST:event_grocerybuttonActionPerformed

    private void maidbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maidbuttonActionPerformed
        CustomerOrderMaidPanel mm = new CustomerOrderMaidPanel(userProcessContainer, userAccount, ecosystem, jSplitPane1);
//        userProcessContainer.add("manageNetworkJPanel",mm);
//        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
//        layout.next(userProcessContainer);        // TODO add your handling code here:
        jSplitPane1.setRightComponent(mm);
    }//GEN-LAST:event_maidbuttonActionPerformed

    private void therpistbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_therpistbuttonActionPerformed
        CustomerOrderTherapistPanel mm = new CustomerOrderTherapistPanel(userProcessContainer, userAccount, ecosystem, jSplitPane1);
//        userProcessContainer.add("manageNetworkJPanel",mm);
//        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
//        layout.next(userProcessContainer);        // TODO add your handling code here:
    jSplitPane1.setRightComponent(mm);
    }//GEN-LAST:event_therpistbuttonActionPerformed

    private void hotelbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hotelbuttonActionPerformed
        // TODO add your handling code here:
        CustomerHotelJPanel mm = new CustomerHotelJPanel(userProcessContainer, userAccount, ecosystem, jSplitPane1);
//        userProcessContainer.add("manageNetworkJPanel",mm);
//        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
//        layout.next(userProcessContainer);
jSplitPane1.setRightComponent(mm);
    }//GEN-LAST:event_hotelbuttonActionPerformed

    private void CovidCare1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CovidCare1ActionPerformed
        // TODO add your handling code here:
          CustomerUpdateInformation mm = new CustomerUpdateInformation(userProcessContainer, userAccount, ecosystem, jSplitPane1);
//        userProcessContainer.add("manageNetworkJPanel",mm);
//        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
//        layout.next(userProcessContainer);
jSplitPane1.setRightComponent(mm);
    }//GEN-LAST:event_CovidCare1ActionPerformed

    private void cartbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cartbuttonActionPerformed
        // TODO add your handling code here:
        CustomerCart mm = new CustomerCart(userProcessContainer, userAccount, ecosystem, jSplitPane1, cust);
        jSplitPane1.setRightComponent(mm);
    }//GEN-LAST:event_cartbuttonActionPerformed

    private void cardbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardbuttonActionPerformed
        // TODO add your handling code here:
        CustomerAddCardDetailsPanel mm = new CustomerAddCardDetailsPanel(userProcessContainer, userAccount, ecosystem, jSplitPane1);
        jSplitPane1.setRightComponent(mm);
    }//GEN-LAST:event_cardbuttonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CovidCare1;
    private javax.swing.JLabel birdiemessage;
    private javax.swing.JButton cardbutton;
    private javax.swing.JButton cartbutton;
    private javax.swing.JPanel container;
    private javax.swing.JButton grocerybutton;
    private javax.swing.JButton hotelbutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton legalbutton;
    private javax.swing.JButton maidbutton;
    private javax.swing.JButton therpistbutton;
    private javax.swing.JLabel title;
    private javax.swing.JLabel title2;
    // End of variables declaration//GEN-END:variables
}
